[package]
name = "prettytable-rs-extensions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable = "0.10.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
